server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    # 내 mysql의 '사용자 root' 내부의 여러 DB들 중에 'security'라는 이름의 DB와 연결시킨다는 의미임.
    username: root
    password: 1234

#사실 아래 'mvc:'~'suffix:'까지는 작성해주지 않아도 됨.
  mvc:
    view:
      prefix: /templates/
      suffix: .mustache

  jpa:
    properties:
      hibernate:
        ddl-auto: create #create update none
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        default_batch_fetch_size: 1000
        naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true


  devtools:
    livereload:
      enabled: true

logging:
  level:
    org:
      springframework: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type: trace
    hibernate: DEBUG
